#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=atcsprune
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=04:00:00
#SBATCH --mem=32000M
#SBATCH --output=slurm_output_%A.out

echo loading Lisa modules...
module purge
module load 2022
module load Miniconda3/4.12.0

cd $HOME/atcs-project/atcs-t1-p2
# Activate your environment
source activate atcs-practical1-2

echo running torch prune file...
srun python prune.py
